package com.abctreinamentos2;
// Generated 03/03/2020 15:48:14 by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private long cdCurso;
	private String nome;
	private long valor;
	private String url;

	public Curso() {
	}

	public Curso(long cdCurso, String nome, long valor, String url) {
		this.cdCurso = cdCurso;
		this.nome = nome;
		this.valor = valor;
		this.url = url;
	}

	public long getCdCurso() {
		return this.cdCurso;
	}

	public void setCdCurso(long cdCurso) {
		this.cdCurso = cdCurso;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public long getValor() {
		return this.valor;
	}

	public void setValor(long valor) {
		this.valor = valor;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
