package com.abctreinamentos;
// Generated 02/03/2020 17:37:35 by Hibernate Tools 4.3.1


/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String descricao;
	private long codigo;
	private Curso curso;
	private long valor;

	public Curso() {
	}

	public Curso(String descricao, long codigo, long valor) {
		this.descricao = descricao;
		this.codigo = codigo;
		this.valor = valor;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}
	public long getValor() {
		return this.valor;
	}

	public void setValor(long valor) {
		this.valor = valor;
	}
	
	@Override
	public String toString() {
		return "Cliente [descricao="+descricao+"valor="+valor+" codigo="+codigo+"]";
	}

}
